### ISSUE TITLE
ibmi_fix_group_check

### ISSUE THREAD

**Issue by cmh716** [IBM/ansible-for-i#152]
Hi,

I am struggling to get ibmi_fix_group_check to work through a proxy.  I have the proxy environment variables set in the playbook, and a get_url download of https://www.ibm.com/support/pages/node/6211843 to a file is successful (200 return), so I know the proxy does not block this specific URL.  The ibmi_fix_group_check always returns

{
"rc": 0,
"count": 1,
"group_info": [
"url": "https://www.ibm.com/support/pages/node/6211843"
"error": "HTTP Error 403: Forbidden"
],

I suspect there are some other sites being called out that perhaps my proxy is blocking but I am not sure which sites.  I don't seem to have issues accessing any of the sites referenced in the ibmi_fix_group_check.py file.  Any ideas?  Thanks

**Comment by JaKo8103** [comment]
Hi,
I am also experiencing a similar error to my colleague.
When I make a curl call to the address from the partition it passes and when I call fix_repo_check_ptf_group already I get:
"fix_group_check_result": {
        "changed": false,
        "count": 1,
        "elapsed_time": "0:00:00.593501",
        "end": "2023-06-05 14:01:59.461052",
        "failed": false,
        "group_info": [
            {
                "error": "HTTP Error 403: Forbidden",
                "url": "https://www.ibm.com/support/pages/node/6211843"

Just executing the SNDPTFORD command from the partition itself works and downloads the appropriate fixes. The proxy does not show any errors during the check as well.

**Comment by robgjertsen1** [comment]
There is an issue with both fix_check and also group_fix_check modules getting the HTTP 403 error from the IBM service site.
I will put out a patch for these files so that the request is not rejected by the HTTP server. The code is using the default
python urllib header for the http/https requests and this no longer works with the web server(s) for the IBM service site; assume an upgrade occurred with web server code that now blocks this request header.
I expect this is your issue versus a problem with proxy server.

I have reproduced the issue myself and also verified an initial fix that resolves the problem.

**Comment by cmh716** [comment]
Thank you both for the responses.  I'm glad to hear I'm not alone, and a fix is coming.

**Comment by robgjertsen1** [comment]
I've placed a patch in the branch gjertsen-patch-fix-check that should
resolve the http 403 error with the fix check modules.

2 module files changed:
plugins/modules/ibmi_fix_check.py
plugins/modules/ibmi_fix_group_check.py

You can copy these two files to the ansible-for-i collection location
on the managing host in the plugins/modules subdirectory, e.g.,

/home/gjertsen/.ansible/collections/ansible_collections/ibm/power_ibmi/plugins/modules

**Comment by cmh716** [comment]
Thank you so much. I have tested it and so far, its working perfectly.

**Comment by robgjertsen1** [comment]
Closing issue. The fix will be included in the next ansible collection release (1.9.2).
