### ISSUE TITLE
fix_group_check dead URL

### ISSUE THREAD

**Issue by cmh716** [IBM/ansible-for-i#157]
It looks like the underlying URL https://www.ibm.com/support/pages/node/6211843 is now dead.

**Comment by cmh716** [comment]
maybe ALL_GROUP_PAGE needs to be changed to "https://www.ibm.com/support/pages/ibm-i-group-ptfs-level" ?

**Comment by robgjertsen1** [comment]
That link for ALL_GROUP_PAGE was a little too specific I guess and is now gone. The general PSP group ptf link you mention looks like what we would want.

**Comment by cmh716** [comment]
Confirmed.  I updated this URL and this module is functional again.

**Comment by cmh716** [comment]
It looks like we also need to update ibmi_fix_check.py

**Comment by robgjertsen1** [comment]
Thanks for the updates (and the changes from psyntium on this). Will incorporate changes with updated URL.

**Comment by robgjertsen1** [comment]
I have updated the internal code repository with the fix and psyntium nicely provided a patch that can be used for now. Will include in 1.9.2 release. Should have 1.9.2 release out in near future.

**Comment by volmcat** [comment]
@robgjertsen1 when can we expect 1.9.2 official push to Galaxy?

**Comment by robgjertsen1** [comment]
Later this month we'll have an update for Galaxy and Redhat. It would have happened sooner, but there are new requirements with Redhat collections passing ansible-lint and I have to include a portion of those changes in this update (and the rest in following release).

**Comment by volmcat** [comment]
How would I change this manually in my own Private Automation Hub? I downloaded the tarball, made the change, and re-compressed to gzip. When I uploaded it complained that the checksum was different, obvious to why that is, but how could we make this change while we wait for the break fix? We can't automate PTF maintenance when this URL is broken

_File plugins/modules/ibmi_fix_group_check.py  sha256sum should be XXXX but the actual sha256sum was XXXX_

**Comment by robgjertsen1** [comment]
OK, I have put out an update for 1.9.2 that has this fix and others, and also put collection update on Galaxy based on need by @volmcat  (can't put that on RH as I'll explain). I've had to focus on a bunch of changes due to Redhat certification (now moving to 2.14+ ansible and a portion of the ansible lint production level changes required) and I can't publish a new collection on RH without these changes. I'll be posting that update *very soon* as release 2.0.0 that has Ansible 2.14+ requirement and Python 3.9+, but it will not really have any new fixes beyond the patch release 1.9.2.

**Comment by robgjertsen1** [comment]
Fixed with 1.9.2.
