### ISSUE TITLE
Ansible check_download_ptf_group

### ISSUE THREAD

**Issue by JaKo8103** [IBM/ansible-for-i#191]
Hello,
I tried today to download the package SF99952 - 750 IBM HTTP Server for i level 14 however, ansible says that such a package already exists:

skipping: [10.XXX.XXX.XX]

TASK [ibm.power_ibmi.fix_repo_check_ptf_group : Set check_ptf_group_fail to True] ***
skipping: [10.XXX.XXX.XX]

TASK [ibm.power_ibmi.fix_repo_check_ptf_group : Check if PTF group information is already in catalog's PTF group information table] ***
skipping: [10.XXX.XXX.XX]

TASK [ibm.power_ibmi.fix_repo_check_ptf_group : Print find PTF group result] ***
ok: [10.XXX.XXX.XX] => {
    "ptf_group_find_result": {
        "changed": false,
        "skip_reason": "Conditional result was False",
        "skipped": true
    }
}

TASK [ibm.power_ibmi.fix_repo_check_ptf_group : Check if PTF group information is already in catalog's download_status table, which means PTF group is downloading.] ***
skipping: [10.XXX.XXX.XX]]

TASK [ibm.power_ibmi.fix_repo_check_ptf_group : Print find download_status table result] ***
skipping: [10.XXX.XXX.XX]]

TASK [End play when no ptf group need to be downloaded] ************************
ok: [10.XXX.XXX.XX]] => {
    "msg": "PTF group information is already in catalog or is already downloading, quit play"
}
My repo in ibmi i:
324         /QIBM/UserData/OS/Service/ECS/PTF/2403645242  SF99952           13               SF99952 750 IBM HTTP Se  2024-02-05 12:10:59

I noticed that on the PSP after entering the group the data is displayed differently:
Asterisk indicates the Fix has special instructions.
Fix Information	Date Added	Legacy	Created	Known issues	Program	Package
FI0074207	26 mar 2024, 19:14 CET	SI79421	14 mar 2024, 18:59 CET	DT321570	5770DG1	2321
FI0074215	26 mar 2024, 19:14 CET	SI78106	14 mar 2024, 18:59 CET	DT321477	5770DG1	2104

**Comment by robgjertsen1** [comment]
Yes, there are some changes with getting away from use of APAR and PTFs.
Specifically, IBM i APARs/PTFs will migrate to Known Issues/Fix Information
See https://www.ibm.com/support/pages/node/7130405

I will look closer at the various impacts. I see there is a note in the IBM i community about this from yesterday.

**Comment by robgjertsen1** [comment]
They have changed the main PSP web page for ptf groups at https://www.ibm.com/support/pages/ibm-i-group-ptfs-level, so
it broke the html file scrapping used in ibmi fix check modules, which then impacts other code like the role fix_repo_check_ptf_group and this specific playbook.
I've just looked at ibmi_fix_group_check so far and can fix that with
the main PSP page for ptf groups, which will hopefully be all that is needed to resolve this issue.
The html scrapping from the fix check code has proven to be problematic, so something that we probably need to reexamine in
the future.

There is a bigger problem with the detailed ptf group web page for getting all the ptfs in that specific group (e.g., https://www.ibm.com/support/pages/uid/nas4SF99952 for SF99952) and need to do something else for that in the future because looks like a group web page source is using javascript now to extract the information, so nothing useful is embedded in the html source itself like in the past. I expect some future turbulence with these changes from APARs/PTFs to Known Issues / Fix Information once they become present in the main ptf group page.

**Comment by robgjertsen1** [comment]
For now I've added a source patch for the fix check modules at https://github.com/IBM/ansible-for-i/tree/gjertsen-patch-fix-check that should resolve the problem
(commit https://github.com/IBM/ansible-for-i/commit/7c234bcf3f60da06e78049897405a1e2c1264221).

I expect that some folks will need a collection update in Galaxy.

**Comment by JaKo8103** [comment]
Hello, I checked and works -  https://github.com/IBM/ansible-for-i/tree/gjertsen-patch-fix-check

**Comment by robgjertsen1** [comment]
This is fixed with 2.0.2 release. There are still some issues with the updated PSP web pages that will need to be addressed but this resolves the more urgent breakage. Things it doesn't resolve are providing all the individual ptfs that comprise a group ptf, along with providing all the dependencies for an individual ptf (pre-reqs, co-reqs, etc.), so seeing how we can get that information again with the fix check modules.
