### ISSUE TITLE
Problem of PSP timeout

### ISSUE THREAD

**Issue by JaKo8103** [IBM/ansible-for-i#198]
Problem of timeout is still active 
We see in: The page you requested cannot be displayed. 500: Internal Server Error

"group_info": [
            {
                "error": "The read operation timed out",
                "url": "https://www.ibm.com/support/pages/ibm-i-group-ptfs-level"
                "timeout": 60,
        "validate_certs": true

**Comment by JaKo8103** [comment]
Today in site ibm-i-group-ptfs-level
I see:
PSP - IBM i Group PTFs with Level
Attached is the list of IBM i PSPs in XML format

[PSPbyNumL](https://www.ibm.com/support/pages/sites/default/files/inline-files/xmldoc.xml)

NOTE:  As of March 18, 2024 this document is being manually updated and therefore may not contain the latest information.  However, the documents referenced will be current.  This page will eventually be replaced by the [Known Issues table](https://www.ibm.com/mysupport/s/product-defect-list?language=en_US&productid=01t500000051Jh7AAE) on the IBM i Product Page.  For more information please visit https://www.ibm.com/support/pages/ibm-i-aparsptfs-have-migrated-known-issuesfix-information
Don't you sometimes need to make some big changes for version 2.0.2 in Galaxy?

**Comment by robgjertsen1** [comment]
There is certainly an issue with the web server if you hit a 60 second time out. Did this just happen once, during a specific time period, or is it happening regularly?

Not clear on the question.

I see the updated verbage on IBM i group PTF web page, which must have been added very recently (wasn't there last week). I am getting more information on the PSP web page changes because there will obviously need to be more changes performed with the collection for checking on the fix information with PSP.

**Comment by JaKo8103** [comment]
Hi,
problem of timeout is regularly

**Comment by robgjertsen1** [comment]
OK, I have not been seeing this in my current testing, but certainly a problem if you are regularly hitting a 60 second time out.

**Comment by robgjertsen1** [comment]
Will track this with issue 204 given they are related issues with the group PTF web page.
