### ISSUE TITLE
Not up-to-date information on IBM i Group PTFs with level

### ISSUE THREAD

**Issue by JaKo8103** [IBM/ansible-for-i#204]
Very often the site is not updated with group level information, which makes manual downloading of data from fix centers a better way. As we know ansible uses this page and we see that it does not cause improvement for us but more and more trouble.
When we go to the link of a particular group we already see the level in it one more. Can it not be so verified by the automaton in ansible ?

**Comment by robgjertsen1** [comment]
Yes, there will need to be changes made here to handle the recent changes with PSP web pages. The main fix group page doesn't reflect the latest group levels as you noted and that page now notes that it will eventually be going away.
It looks like we can switch to using PSP xml files to obtain the group fix information such as starting with listing of all group fixes
here https://public.dhe.ibm.com/services/us/igsc/PSP/xmldoc.xml and then looking at individual xml file for a specific fix such as https://public.dhe.ibm.com/services/us/igsc/PSP/SF99667.xml for all the individual fixes used.
The handling for individual fixes and their dependencies due to PSP web changes still requires more investigation.

**Comment by robgjertsen1** [comment]
I will also use this issue to also track the noted timeout of group PTF page at times: issue 198 "Problem of PSP timeout".
My expectation is that using XML pages for group ptfs will also resolve the other issue.

**Comment by JaKo8103** [comment]
Rob,
in last six days i have this information:
TASK [ibm.power_ibmi.fix_repo_check_ptf_group : Print the latest PTF group information] ***
ok: [10.102.169.86] => {
    "fix_repo_check_ptf_group_fix_group_check_result": {
        "changed": false,
        "count": 1,
        "elapsed_time": "0:00:01.163447",
        "end": "2024-08-29 07:02:52.379892",
        "failed": false,
        "group_info": [
            {
                "**error": "**HTTP Error 400: Bad Request**",**
                "url": "[https://www.ibm.com/support/pages/ibm-i-group-ptfs-level"](https://www.ibm.com/support/pages/ibm-i-group-ptfs-level%22)
            }
        ],
        "http_agent": "ansible/ibm.power_ibmi",
        "rc": 0,
        "start": "2024-08-29 07:02:51.216445",
        "stderr": "",
        "stderr_lines": [],
        "timeout": 60,
        "validate_certs": true

**Comment by robgjertsen1** [comment]
OK, thanks for pointing that out. I will check on that and may need to do an update sooner than expected to use the xml files for this information instead of the group ptf html pages.

**Comment by robgjertsen1** [comment]
Can you provide the task code excerpt for that failed query or the group PTF information for the query? I am not seeing a problem with some queries using ibmi_fix_group_check by itself (called by role fix_repo_check_ptf_group), but I'm also certainly not checking the same PTF group.

**Comment by JaKo8103** [comment]
Hi,
I had the problem between 27.08 and 29.08 
now works

**Comment by robgjertsen1** [comment]
Updates with release 3.2.0 should help here with group PTF check now using XML files that have the latest information.
