### ISSUE TITLE
ibmi_device_vary module does not show status of changed

### ISSUE THREAD

**Issue by robinsg** [IBM/ansible-for-i#36]
**Issue**
When using ibmi_device_vary to vary ON a device which is varied OFF the status returned is OK=1 when I would expect it to be changed=1.

**Playbook**

- name: Ensure device is varied on
 hosts: all
 gather_facts: no
  collections:
    - ibm.power_ibmi

  tasks:
- name: Vary on device
 ibmi_device_vary:
&nbsp;&nbsp;      device_list:
&nbsp;&nbsp;&nbsp;&nbsp;- 'OPT01'
&nbsp;&nbsp;      status: '*ON'
&nbsp;&nbsp;      joblog: true

**Output**

robinsg@VM-T490-WIN10-01:~/ansible/ibmi/plays$ ansible-playbook vary_on_device.yml

PLAY [Ensure device is varied on] ********************************************************************************************************************************************************************************************************************

TASK [Vary on device] ********************************************************************************************************************************************************************************************************************************
ok: [XXYYZZ01]

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************
XXYYZZ01                   : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  

The results are the same if i vary OFF a device which is varied ON.

**Comment by jpehrson** [comment]
Both the "ok" and "changed" statuses indicate a successful task.  The "ok" status is returned when the module completed its action successfully, but didn't create, modify, or change an object on the managed node.  The "changed" status is returned when a module creates or modifies a physical object on the managed node.  In your scenario, the varying on/off of a device does not actually create or change a physical object, but simply updates the status of the device, which is the purpose of the ibmi_device_vary module, which is why the "ok" status is returned (The module successfully completed its action).  If the module would have created or changed an physical object, then a "changed" status would have been returned.  The status returned depends on the module being executed and the action(s) it performs.

I understand that it sounds like varying on/off a device is "changing" its status, but this operation doesn't actually create any objects nor change the physical properties of the object.  For example, if the ansible module would have created a new device or changed the actual device properties, like its name, then a status of "changed" would have been returned instead of "ok".

https://docs.ansible.com/ansible/latest/reference_appendices/common_return_values.html#changed

**Comment by robinsg** [comment]
Fair enough, I agree completely now I understand that more clearly.

Thank you.
