### ISSUE TITLE
sync_apply_individual_ptfs

### ISSUE THREAD

**Issue by Ludovic-Menard** [IBM/ansible-for-i#87]
Hello,
When I use the playbook sync_apply_individual_ptfs, I receive an error the task "Transfer image to target_system".
I use verbose to debut and the message is :
The full traceback is:
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 146, in run
res = self._execute()
File "/usr/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 654, in _execute
result = self._handler.run(task_vars=variables)
File "/home/team0/.ansible/collections/ansible_collections/ibm/power_ibmi/plugins/action/ibmi_synchronize_files.py", line 88, in run
result.update(self._execute_module('ibmi_sync_files', module_args=_tmp_args))
File "/usr/lib/python3.6/site-packages/ansible/plugins/action/init.py", line 831, in _execute_module
(module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
File "/usr/lib/python3.6/site-packages/ansible/plugins/action/init.py", line 165, in _configure_module
use_vars = task_vars.get('ansible_delegated_vars')[self._task.delegate_to]
TypeError: 'NoneType' object is not subscriptable
fatal: [10.7.19.58]: FAILED! => {
"msg": "Unexpected failure during module execution.",
"stdout": ""
}
I uploaded the command result/
Thanks for your help.
Ludo
[result_sync.txt](https://github.com/IBM/ansible-for-i/files/6161608/result_sync.txt)

**Comment by LiJunBJZhu** [comment]
@pengzengyufish may you take a look at this?

**Comment by changlexc** [comment]
This is due to the new Ansible release which has an update for action modules especially for delegate to. We have already fixed this issue and will deliver the fix release in near feature(may be this week). For a quick fix, you can change the source file ansible-for-i/plugins/action/ibmi_synchronize_files.py line 88 
from 
result.update(self._execute_module('ibmi_sync_files', module_args=_tmp_args))
to
result.update(self._execute_module('ibmi_sync_files', module_args=_tmp_args, task_vars=task_vars))

**Comment by LiJunBJZhu** [comment]
I think the fix has been released within 1.2.2.

**Comment by Ludovic-Menard** [comment]
Hello. Thanks a lot. Yes it solved with release 1.2.2.
